package fun.wxy.annoy_o_tron.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SHIP".
 */
public class Ship {

    private Long id;
    /** Not-null value. */
    private String store_name;
    /** Not-null value. */
    private String category;
    /** Not-null value. */
    private String item_no;
    /** Not-null value. */
    private String item_name;
    private int order_qty;
    private int ship_qty;
    /** Not-null value. */
    private String order_type;
    private double price;
    private String ship_no;
    /** Not-null value. */
    private String status;

    public Ship() {
    }

    public Ship(Long id) {
        this.id = id;
    }

    public Ship(Long id, String store_name, String category, String item_no, String item_name, int order_qty, int ship_qty, String order_type, double price, String ship_no, String status) {
        this.id = id;
        this.store_name = store_name;
        this.category = category;
        this.item_no = item_no;
        this.item_name = item_name;
        this.order_qty = order_qty;
        this.ship_qty = ship_qty;
        this.order_type = order_type;
        this.price = price;
        this.ship_no = ship_no;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getStore_name() {
        return store_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStore_name(String store_name) {
        this.store_name = store_name;
    }

    /** Not-null value. */
    public String getCategory() {
        return category;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory(String category) {
        this.category = category;
    }

    /** Not-null value. */
    public String getItem_no() {
        return item_no;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setItem_no(String item_no) {
        this.item_no = item_no;
    }

    /** Not-null value. */
    public String getItem_name() {
        return item_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setItem_name(String item_name) {
        this.item_name = item_name;
    }

    public int getOrder_qty() {
        return order_qty;
    }

    public void setOrder_qty(int order_qty) {
        this.order_qty = order_qty;
    }

    public int getShip_qty() {
        return ship_qty;
    }

    public void setShip_qty(int ship_qty) {
        this.ship_qty = ship_qty;
    }

    /** Not-null value. */
    public String getOrder_type() {
        return order_type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOrder_type(String order_type) {
        this.order_type = order_type;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public String getShip_no() {
        return ship_no;
    }

    public void setShip_no(String ship_no) {
        this.ship_no = ship_no;
    }

    /** Not-null value. */
    public String getStatus() {
        return status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStatus(String status) {
        this.status = status;
    }

}
