package fun.wxy.annoy_o_tron.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SHIP_HEADER".
 */
public class ShipHeader {

    private Long id;
    /** Not-null value. */
    private String ship_date;
    /** Not-null value. */
    private java.util.Date created_date;

    public ShipHeader() {
    }

    public ShipHeader(Long id) {
        this.id = id;
    }

    public ShipHeader(Long id, String ship_date, java.util.Date created_date) {
        this.id = id;
        this.ship_date = ship_date;
        this.created_date = created_date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getShip_date() {
        return ship_date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setShip_date(String ship_date) {
        this.ship_date = ship_date;
    }

    /** Not-null value. */
    public java.util.Date getCreated_date() {
        return created_date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreated_date(java.util.Date created_date) {
        this.created_date = created_date;
    }

}
